### ISSUE TITLE
Error: Process completed with exit code 1. flutter ci/cd

### ISSUE THREAD

**Issue by divyesh008** [thoughtbot/appraisal#187]
I have tried to setup CI/CD using flutter actions but when I am committing code and action run it gives this error:

```dart
Run flutter build windows
Running "flutter pub get" in flutter_tools...                       3.8s
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Error: Process completed with exit code 1.
```

![flutter cicd](https://user-images.githubusercontent.com/10617244/126668212-f6775258-c713-42e2-8372-43411b2e2f9c.png)

## My dart.yml

```
name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
            java-version: '12.x'
            
      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.2'
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
```
